name: dotnet-integration

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'GraphRag.slnx'
      - '.github/workflows/dotnet-integration.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'GraphRag.slnx'
      - '.github/workflows/dotnet-integration.yml'

jobs:
  test:
    name: Integration tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      MSBUILDTERMINALLOGGER: 'false'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET 9 preview
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore tests/GraphRag.Tests.Integration/GraphRag.Tests.Integration.csproj

      - name: Run integration tests
        run: dotnet test tests/GraphRag.Tests.Integration/GraphRag.Tests.Integration.csproj --configuration Release
